[package]
name = "mercury-mapper"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.2.1"
devicemapper = "0.34.4"
nix = "0.29.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
